apiVersion: v1
kind: Pod
metadata:
  name: pod-with-app
  labels:
    app: myapp
  namespace: default
spec:
  containers:
  — name: hello-world
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
#    imagePullPolicy: IfNotPresent
