apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: role-binding
subjects:
- kind: User
  name: usertest
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: user-role
  apiGroup: rbac.authorization.k8s.io