apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume
  namespace: myvolume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      containers:
      - name: busybox
        image: busybox:1.28
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        command: ['sh', '-c', 'while true; do echo "$(date +%H:%M:%S)" >> /etc/output/localtime.txt; sleep 5; done']
        volumeMounts:
        - name: vol
          mountPath: /etc/output

      - name: multitool
        image: wbitt/network-multitool
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        volumeMounts:
        - name: vol
          mountPath: /etc/input

      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: pvc-vol
