apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol
  namespace: myvolume
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions: hard
#        - nfsvers=4.0
    nfs:
      path: /path/on/nfs/server
      server: nfs-server-ip-address

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vol
  namespace: myvolume
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
