apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vol
  namespace: myvolume
spec:
  storageClassName: "microk8s-hostpath"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
