apiVersion: v1
kind: Service
metadata:
  name: ngnix-svc
spec:
  selector:
    app: nginx-multitool
  ports:
  - name: nginx
    port: 9001
    protocol: TCP
    targetPort: 80
  - name: multitool
    port: 9002
    protocol: TCP
    targetPort: 8080