apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool
  labels:
    app: multitool-back
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool-back
  template:
    metadata:
      labels:
        app: multitool-back
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8801"
        ports:
        - containerPort: 8080
