apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: volume
  namespace: default
spec:
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: vol
          mountPath: /etc/input
      volumes:
      - name: vol
        hostPath:
          path: /var/log
