apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-web
  namespace: myweb
data:
  index.html: |
    <html>
    <body>
      <h1> Hello world!!! </h1>
    </body>
    </html>

---

apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
  namespace: myweb
data:
  tls.crt: aHR0cHNfc2VjcmV0X2NlcnQK #base64 encode cert
  tls.key: aHR0cHNfc2VjcmV0X2tleQo= #base64 encode key
type: kubernetes.io/tls